- name : variables
  hosts: local
  connection: local
  vars: #play level variables, global variables
    val1= 4
    string1= "from playlevel"
  tasks:  
  - name: print the variable
    ansible.builtin.debug:
      msg : " print value {{val1}} & string value {{string1}}"