- name : variables
  hosts: local
  connection: local
  vars: #play level variables, global variables
    val1= 4
    string1= "from playlevel"
  Tasks:
  - name: print the variable
    vars:  #task level variables, local variables, accessible within task,task variables can override play level variables
      string1="from task"
    ansible.builtin.debug:
      msg : " print value {{val1}} & string value {{string1}}"
  
  
  - name: print the variable
    ansible.builtin.debug:
      msg : " print value {{val1}} & string value {{string1}}"