- name: variables
  hosts: local
  connection: local
  # vars: # PLAY level variables
  #   GREET: "PLAY"
  # vars_files:
  #   - vars1.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: Enter the value
  #   private: false
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hie from {{ GREET }}"

#1. Command line or args    #ansible-playbook -i inventory.ini <playbook>.yaml -e "GREET=ARGS"
#2. Task level
#3. Files
#4. Prompt
#5. Play
#6. Inventory
#7. Roles