- name: DevOps skills
  hosts: local
  connection: local
  vars:
    name: "AWS" # string
    nummber : 120 #number
    topics: # list, [] this means list
    - linux
    - shell
    - ansible
    - AWS
    live: true # boolean
    tools: #map, {} this means map
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks:
  - name: print information
    ansible.builtin.debug:
    msg: "name {{name}} number {{number}} skills are: {{topics}} true? {{live}} tools: {{tools}}"