
- name: shell vs Command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command in shell module
    #ansible.builtin.command: ls -ltr > /tmp/output.txt #no access to shell variables, redirections, pipes etc
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute ls command in command module
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    #ansible.builtin.command: ls -ltr
    ansible.builtin.command: lsss -ltrssfff
    register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"

#Command will execute from outside where shell will login to the server to execute.
#Shell can we used for complex.